# Generated by Django 4.2.4 on 2023-09-06 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_remove_alumno_comision_remove_curso_comision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='comision',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.comision'),
        ),
    ]
